### ISSUE TITLE
Aggiungere codifica password per invio al db

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#49]
*Documento in cui si trova il problema*: 
Manuale Sviluppatore
Activity #37

*Descrizione del problema*:
Aggiungere codifica password per invio al db

Link task: [https://bugbusters.teamwork.com/tasks/6938670](https://bugbusters.teamwork.com/tasks/6938670)

**Comment by korut94** [comment]
Scusa @mdipirro non capisco cosa tu intendi. Riguarda la lamentela del prof se la password inviata al server fosse in chiaro? Se è cosi non so come viene trattata.

**Comment by WeissL** [comment]
La sistemiamo passando quella richiesta in https?

**Comment by korut94** [comment]
Io sono la persona meno idonea a risponderti. Se Heroku lo permette chiedi a @Polpetta.

**Comment by Polpetta** [comment]
La password viene inviata in chiaro?
Se si non va bene, dovete in qualche modo criptarla e spedirla. Per l'https
non lo so @WeissL, siamo sicuri che il servizio usi sempre l'https?

Comunque @mdipirro sicuro che non si riferisse al fatto che usiamo un json
in chiaro con i parametri del database? (Per di più salvati sul repository
di git)
Il 04 giu 2016 10:17, "Andrea Mantovani" <notifications@github.com> ha
scritto:

Io sono la persona meno idonea a risponderti. Se Heroku lo permette chiedi
a @Polpetta <https://github.com/Polpetta>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/BugBusterSWE/MaaS/issues/49#issuecomment-223743594>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AFp09wNFX4WR06j9BQAc8qXuISWOhKUDks5qITSVgaJpZM4IpDDY>
.

**Comment by WeissL** [comment]
@Polpetta il file con le credenziali in realtà è inevitabile comunque non si può accedere a quel file dall'esterno.... più che altro come facciamo con sta storia delle password? non so quanto tempo ci voglia a sistemare quello

**Comment by Polpetta** [comment]
Penso che non ci faccia perdere troppo tempo applicare un algoritmo di
criptazione simmetrica tipo bluefish (o versioni successive).
@WeissL aggiungi questo punto all'ordine del giorno della riunione di
lunedì che ne discutiamo col gruppo.
Il 04 giu 2016 18:20, "Luca" <notifications@github.com> ha scritto:

**Comment by mdipirro** [comment]
@polpetta la stringa di connessione di mongoose è fatta così e secondo me si riferisce alle password degli utenti che sono in chiaro. @weiss non basta usare un modulo insulso che cifra la password lato client e memorizzare la password cifrata. Non serve fare cose mega fighe ragazzi, basta che la password non sia in chiaro nel db. Se confronti la password dopo la cifratura lato client a noi non cambia nulla, semplicemente viene cifrata lato client

**Comment by mdipirro** [comment]
Una cosa tipo questa, basta una ricerca di 2 minuti su google: https://www.npmjs.com/package/crypto-js

**Comment by Polpetta** [comment]
Ah ok ho capito qual'e' il problema. Io pensavo che volessi che tutto il flusso di dati fosse sicuro. Se ti serve solo la password che sia "cifrata" basta fare 3-4 volte uno sha-256 @mdipirro.

**Comment by mdipirro** [comment]
Nono mi basta la password. Anche una volta sola, l'importante è che non sia in chiaro

**Comment by Polpetta** [comment]
Se lo fai una volta sola potrebbe lamentarsi che soffre dell'attacco del reverse sha (o sha lookup), che è abbastanza semplice:
http://sha1.gromweb.com/
Prendi lo sha lo metti in un sito come questo è hai il valore.

Poi vedi te @mdipirro, è che se cominciamo con la sicurezza non finiamo più😂

**Comment by WeissL** [comment]
Scusate, la password è cifrata con crypto, con sale crittografico a 16 caratteri e 1000 iterazioni di hashing.. Mi sembra sia già abbastanza cifrata, no? io non penso si riferisse a quello

**Comment by Polpetta** [comment]
@mdipirro Che facciamo? E' possibile chiedere chiarimenti al prof per questo? Che almeno sappiamo chiaramente cosa voleva ed evitiamo di scervellarsi per nulla :blush:

**Comment by mdipirro** [comment]
Si certo, chiedete

**Comment by korut94** [comment]
Sposto l'issue nell'activity #37 in quanto compito da svolgere nel frontend.
